# ===================================================== #
#
# Autoload Helpers:
#   Helpers/s to be autoloaded must have the same spelling 
#   and capitalizations as the helpers
#     List of available helpers: 'form_validation'
#
# ===================================================== #
helpers:

# ===================================================== #
#
# Autoload Model:
#   Model/s to be autoloaded must have the same spelling 
#   and capitalizations
#   
#   Example:
#     models:
#       - "SampleModel"
#
# ===================================================== #
models: