# =================================================== #
# Key value pair for the route to controller methods
# Example:
#
# ClassFileController:
#   "/test_url": "testMethod"
#
# =================================================== #

WelcomeController:
  "/": "welcome"